### ISSUE TITLE
Error stopping node: window is not defined

### ISSUE THREAD

**Issue by gabeale** [zuhito/node-red-contrib-mqtt-broker#19]
Hi,
unfortunately I'm not able to properly configure "mqtt in" palette because I'm receiving the following error messages:

Error stopping node: TypeError: Cannot read property 'exit' of undefined

ReferenceError: window is not defined

I have tried several configs but nothing to do.
Scope is get the GPIO 0 status of MyESP8266 mega through Node-Red.
Can you help me?
Thanks guys
Alex

**Comment by martin-doyle** [comment]
Sorry but this node here is a MQTT broker, What you are referring to is the standard MQTT In node which is part of the [Node Red Core IO](https://github.com/node-red/node-red/tree/master/nodes/core/io) nodes.
You might ask there or give us some more details. If you run `node-red -v` what error messages do you get? Thank you.

**Comment by gabeale** [comment]
Thanks Martin, at the end I solved this issue because I noted a bad config in Node Red MQTT function.
Now plublishing and subscribing are working perfectly.
Thank you again for prompt support.
