### ISSUE TITLE
About user auth

### ISSUE THREAD

**Issue by camilordx** [zuhito/node-red-contrib-mqtt-broker#23]
I tried to use the user and password authentication, but it doesn't work, every connection pass by.

**Comment by martin-doyle** [comment]
Could you provide some more details, please? How did you setup the broker? How did you test the authentication?

**Comment by LuFlo** [comment]
I have the same issue. I just provided the credentials in the mosca node, but it doesn't seem to have any effect. I can publish and subscribe with wrong passwords. As a publisher I have a paho java client and as subscriber I tested it with the mqtt node directly in node-red. Although both (subscriber and publisher) use wrong credentials, I can post and subscribe messages.
