### ISSUE TITLE
Not installing on Node-Red

### ISSUE THREAD

**Issue by moelha** [zuhito/node-red-contrib-mqtt-broker#7]
I am trying to install it on the Node-Red present on the IBM Bluemix platform. When I download it from the palette, the installation is unsuccessful with the following error:

`Error: Command failed: npm install --save --save-prefix="~" --production node-red-contrib-mqtt-broker@0.2.1
npm WARN engine mosca@0.28.1: wanted: {"node":">=0.10.10 <0.13"} (current: {"node":"4.8.4","npm":"2.15.11"})
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mongodb@1.4.40: Please upgrade to 2.2.19 or higher
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
In file included from ../src/reader.h:4:0,
                 from ../src/hiredis.cc:3:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../node_modules/nan/nan.h:335:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
     return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                          ...`

**Comment by zuhito** [comment]
Thank you for your report. This node cannot run on Node-RED on Bluemix because Could Foundry instance uses only HTTP or HTTPS port. So the instance cannot use MQTT port even if the build error is solved. Please another MQTT broker like Watson IoT Platform insted of that.

**Comment by moelha** [comment]
Thanks!
